[package]
name = "rsdroid"
version = "0.1.0"
authors = ["David Allison <davidallisongithub@gmail.com>"]
edition = "2018"

[lib]
crate_type = ["dylib"]

[dependencies]
jni = { version = "0.17.0", default-features = false }
libc = { version = "0.2" } # 0.2.3 required for libc::syscall
anki = { path = "../anki/rslib" }