[target.x86_64-apple-darwin]
# Required for cross-compilation -  not used as we're restricted to build on MacOS by apple ToS.
# So cross-compilation is only required for Linux/Windows, which have more sensible toolchains
# linker = "x86_64-apple-darwin14-clang"
# ar = "x86_64-apple-darwin14-ar"