name: CI
on: push

# Some of the commands here were added to attempt to get a build on a local Ubuntu VirtualBox
# using https://github.com/nektos/act/
# I didn't get this working, and these should likely be removed 
# This may also mean we're performing too many install steps
# https://github.com/david-allison-1/Anki-Android-Backend/issues/7

jobs:
  test:
    runs-on: ubuntu-latest
    # env:
      # required for "act": https://github.com/nektos/act/issues/265
      # ANDROID_SDK_ROOT: /usr/lib/android/sdk 
      # ANDROID_HOME: /usr/lib/android/sdk
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true' # anki is a submodule

    # install cargo
    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: 1.45.1 # arbitrary - known working version
        override: true
        components: rustfmt, clippy

    # actions-rs only accepts "target" (although a "targets" param to be added in v2). We need 7 targets.
    - name: Install Rust Targets
      run: .github/scripts/install_rust_targets.sh
   
   # Attempt to get "act" working on a local VM
   # - name: Install Android SDK
   #   run: sudo apt update && sudo apt install android-sdk
      
    - name: Build
      run: ./gradlew clean assembleDebug -DtestBuildType=debug -Dorg.gradle.daemon=false -Dorg.gradle.console=plain # assembleAndroidTest 