name: Publish rsdroid (Linux)
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true' # anki is a submodule

    # i18n did not seem to be handled
    - name: Init i18n submodule
      run: git submodule update --init --recursive

    - name: Install NDK
      run: .github/scripts/install_ndk.sh 21.3.6528147
         
    - name: Install linker
      run: .github/scripts/linux_install_x86_64-unknown-linux-gnu-gcc.sh

    # install cargo
    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true

    # actions-rs only accepts "target" (although a "targets" param to be added in v2). We need 7 targets.
    - name: Install Rust Targets
      run: .github/scripts/install_rust_targets.sh

    - name: Install google protobuf compiler
      run: |
              sudo apt-get install python3-setuptools 
              pip3 install protobuf-compiler
              .github/scripts/protoc_gen_deps.py

    - name: Build
      run: ./gradlew clean assembleRelease -DtestBuildType=release -Dorg.gradle.daemon=false -Dorg.gradle.console=plain
      
    - name: Publish AAR to Maven
      env:
        ORG_GRADLE_PROJECT_SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
        ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SONATYPE_NEXUS_USERNAME: david-allison-1
        SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      run: ./gradlew rsdroid:uploadArchives -DtestBuildType=release -Dorg.gradle.daemon=false -Dorg.gradle.console=plain