name: Build JAR for Robolectric Testing
on: push

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true' # anki is a submodule

    # i18n did not seem to be handled
    - name: Init i18n submodule
      run: git submodule update --init --recursive

    # install cargo
    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly # nightly is currently required for Robolectric Testing
        override: true
        components: rustfmt, clippy

    # actions-rs only accepts "target" (although a "targets" param to be added in v2). We need 7 targets.
    - name: Install Rust Targets
      run: .github/scripts/install_rust_robolectric_targets.sh

    - name: Install x86_64-w64-mingw32-gcc
      run: brew install mingw-w64 && x86_64-w64-mingw32-gcc -v

    # TODO: Export above didn't seem to work 
    # cd osxcross/target/bin &&
    # export ANKIDROID_MACOS_CC="$PWD/x86_64-apple-darwin14-cc" &&
    # export PATH=$PATH:$(pwd) &&
    # echo $PATH &&
    # cd ../../../ &&
    # x86_64-apple-darwin14-clang -v &&
    # echo "ANKIDROID_MACOS_CC is ${ANKIDROID_MACOS_CC}" &&
    - name: Build JAR
      run: >
              export ANKIDROID_MACOS_CC=cc &&
              ./gradlew clean rsdroid-testing:build rsdroid-testing:build -Dorg.gradle.project.macCC=$ANKIDROID_MACOS_CC -DtestBuildType=debug -Dorg.gradle.daemon=false -Dorg.gradle.console=plain
              
    - name: List compiled assets
      run: >
              cd rsdroid-testing/assets &&
              ls -l
              
    - name: Upload rsdroid-testing JAR as artifact
      uses: actions/upload-artifact@v2
      with:
        name: rsdroid-testing
        if-no-files-found: error
        path: rsdroid-testing/build/libs/rsdroid-testing.jar